roles:
	- name:kube-masters
	  num: 1
	  hostnamePrefix: abchost
    - name: kube-nodes
	  num: 2
	  minNum: 1
	- name: etcd
	  num: 3
	- name: registry
	  ipAddresses:
		- 10.62.71.77
reuse_group:
	- group_name: kube1
	  members:
		- kube-masters
		- etcd